### ISSUE TITLE
Application can't handle complex encoding in description field

### ISSUE THREAD

**Issue by cvitter** [cvitter/mattermost-jira-bridge#1]
40.113.218.89 - - [05/Jul/2018 19:41:43] "POST /jira/PRJX?user_id=craig&user_key=craig HTTP/1.1" 200 -
[2018-07-05 19:42:50,771] ERROR in app: Exception on /jira/PRJX [POST]
Traceback (most recent call last):
  File "/home/sales-demo/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sales-demo/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sales-demo/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sales-demo/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sales-demo/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "jira.py", line 241, in hooks
    handle_actions(project_key, request.get_json())
  File "jira.py", line 199, in handle_actions
    format_changelog(data["changelog"]["items"]),
  File "jira.py", line 142, in format_changelog
    str(item["toString"]) + "_\n"
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 56: ordinal not in range(128)

**Comment by cvitter** [comment]
Bug squashed for now via .encode('ascii','ignore').strip() and commit https://github.com/cvitter/mattermost-jira-bridge/commit/01c02291524e4f901d53a5d5161742d037706f15
